// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/microservices-development-hse/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// AnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type AnalyticsRepository struct {
	mock.Mock
}

// CalculateTimeInState provides a mock function with given fields: ctx, projectID
func (_m *AnalyticsRepository) CalculateTimeInState(ctx context.Context, projectID int) (map[string][]float64, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for CalculateTimeInState")
	}

	var r0 map[string][]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (map[string][]float64, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) map[string][]float64); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestSnapshot provides a mock function with given fields: ctx, projectID, reportType
func (_m *AnalyticsRepository) GetLatestSnapshot(ctx context.Context, projectID int, reportType string) (*models.AnalyticsSnapshot, error) {
	ret := _m.Called(ctx, projectID, reportType)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSnapshot")
	}

	var r0 *models.AnalyticsSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*models.AnalyticsSnapshot, error)); ok {
		return rf(ctx, projectID, reportType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *models.AnalyticsSnapshot); ok {
		r0 = rf(ctx, projectID, reportType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AnalyticsSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, projectID, reportType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOpenTasksBottlenecks provides a mock function with given fields: ctx, projectID
func (_m *AnalyticsRepository) GetOpenTasksBottlenecks(ctx context.Context, projectID int) ([]models.OpenTaskDuration, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenTasksBottlenecks")
	}

	var r0 []models.OpenTaskDuration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.OpenTaskDuration, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.OpenTaskDuration); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OpenTaskDuration)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectComplexity provides a mock function with given fields: ctx, projectID
func (_m *AnalyticsRepository) GetProjectComplexity(ctx context.Context, projectID int) ([]models.TaskComplexity, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectComplexity")
	}

	var r0 []models.TaskComplexity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.TaskComplexity, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.TaskComplexity); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TaskComplexity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskPriorityDistribution provides a mock function with given fields: ctx, projectID
func (_m *AnalyticsRepository) GetTaskPriorityDistribution(ctx context.Context, projectID int) ([]models.DistributionItem, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskPriorityDistribution")
	}

	var r0 []models.DistributionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.DistributionItem, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.DistributionItem); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DistributionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskStatusDistribution provides a mock function with given fields: ctx, projectID
func (_m *AnalyticsRepository) GetTaskStatusDistribution(ctx context.Context, projectID int) ([]models.DistributionItem, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskStatusDistribution")
	}

	var r0 []models.DistributionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.DistributionItem, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.DistributionItem); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DistributionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveSnapshot provides a mock function with given fields: ctx, snapshot
func (_m *AnalyticsRepository) SaveSnapshot(ctx context.Context, snapshot *models.AnalyticsSnapshot) error {
	ret := _m.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for SaveSnapshot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AnalyticsSnapshot) error); ok {
		r0 = rf(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAnalyticsRepository creates a new instance of AnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsRepository {
	mock := &AnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
