// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/microservices-development-hse/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthorRepository is an autogenerated mock type for the AuthorRepository type
type AuthorRepository struct {
	mock.Mock
}

// CreateAuthor provides a mock function with given fields: author
func (_m *AuthorRepository) CreateAuthor(author *models.Author) error {
	ret := _m.Called(author)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Author) error); ok {
		r0 = rf(author)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAuthorByExternalID provides a mock function with given fields: externalID
func (_m *AuthorRepository) GetAuthorByExternalID(externalID string) (*models.Author, error) {
	ret := _m.Called(externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByExternalID")
	}

	var r0 *models.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Author, error)); ok {
		return rf(externalID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Author); ok {
		r0 = rf(externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthorByName provides a mock function with given fields: name
func (_m *AuthorRepository) GetAuthorByName(name string) (*models.Author, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByName")
	}

	var r0 *models.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Author, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Author); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAuthor provides a mock function with given fields: author
func (_m *AuthorRepository) UpdateAuthor(author *models.Author) error {
	ret := _m.Called(author)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuthor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Author) error); ok {
		r0 = rf(author)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthorRepository creates a new instance of AuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorRepository {
	mock := &AuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
