// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	connector "github.com/microservices-development-hse/backend/internal/generated/connector"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ConnectorServiceClient is an autogenerated mock type for the ConnectorServiceClient type
type ConnectorServiceClient struct {
	mock.Mock
}

// FetchRemoteProjects provides a mock function with given fields: ctx, in, opts
func (_m *ConnectorServiceClient) FetchRemoteProjects(ctx context.Context, in *connector.Empty, opts ...grpc.CallOption) (*connector.ProjectList, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FetchRemoteProjects")
	}

	var r0 *connector.ProjectList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *connector.Empty, ...grpc.CallOption) (*connector.ProjectList, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *connector.Empty, ...grpc.CallOption) *connector.ProjectList); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.ProjectList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *connector.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TriggerProjectImport provides a mock function with given fields: ctx, in, opts
func (_m *ConnectorServiceClient) TriggerProjectImport(ctx context.Context, in *connector.ImportRequest, opts ...grpc.CallOption) (*connector.ImportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TriggerProjectImport")
	}

	var r0 *connector.ImportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *connector.ImportRequest, ...grpc.CallOption) (*connector.ImportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *connector.ImportRequest, ...grpc.CallOption) *connector.ImportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connector.ImportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *connector.ImportRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConnectorServiceClient creates a new instance of ConnectorServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectorServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectorServiceClient {
	mock := &ConnectorServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
