// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/microservices-development-hse/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// HistoryRepository is an autogenerated mock type for the HistoryRepository type
type HistoryRepository struct {
	mock.Mock
}

// AddStatusChanges provides a mock function with given fields: history
func (_m *HistoryRepository) AddStatusChanges(history *models.StatusChanges) error {
	ret := _m.Called(history)

	if len(ret) == 0 {
		panic("no return value specified for AddStatusChanges")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.StatusChanges) error); ok {
		r0 = rf(history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByIssueID provides a mock function with given fields: issueID
func (_m *HistoryRepository) DeleteByIssueID(issueID int) error {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIssueID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(issueID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByAuthorID provides a mock function with given fields: authorID
func (_m *HistoryRepository) GetByAuthorID(authorID int) ([]models.StatusChanges, error) {
	ret := _m.Called(authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAuthorID")
	}

	var r0 []models.StatusChanges
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.StatusChanges, error)); ok {
		return rf(authorID)
	}
	if rf, ok := ret.Get(0).(func(int) []models.StatusChanges); ok {
		r0 = rf(authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.StatusChanges)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(authorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistoryByIssueID provides a mock function with given fields: issueID
func (_m *HistoryRepository) GetHistoryByIssueID(issueID int) ([]models.StatusChanges, error) {
	ret := _m.Called(issueID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryByIssueID")
	}

	var r0 []models.StatusChanges
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.StatusChanges, error)); ok {
		return rf(issueID)
	}
	if rf, ok := ret.Get(0).(func(int) []models.StatusChanges); ok {
		r0 = rf(issueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.StatusChanges)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(issueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHistoryRepository creates a new instance of HistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HistoryRepository {
	mock := &HistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
