// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/microservices-development-hse/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// IssueRepository is an autogenerated mock type for the IssueRepository type
type IssueRepository struct {
	mock.Mock
}

// CreateIssue provides a mock function with given fields: issue
func (_m *IssueRepository) CreateIssue(issue *models.Issue) error {
	ret := _m.Called(issue)

	if len(ret) == 0 {
		panic("no return value specified for CreateIssue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Issue) error); ok {
		r0 = rf(issue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteIssue provides a mock function with given fields: id
// func (_m *IssueRepository) DeleteIssue(id int) error {
// 	ret := _m.Called(id)

// 	if len(ret) == 0 {
// 		panic("no return value specified for DeleteIssue")
// 	}

// 	var r0 error
// 	if rf, ok := ret.Get(0).(func(int) error); ok {
// 		r0 = rf(id)
// 	} else {
// 		r0 = ret.Error(0)
// 	}

// 	return r0
// }

// GetIssueByExternalID provides a mock function with given fields: externalID
// func (_m *IssueRepository) GetIssueByExternalID(externalID string) (*models.Issue, error) {
// 	ret := _m.Called(externalID)

// 	if len(ret) == 0 {
// 		panic("no return value specified for GetIssueByExternalID")
// 	}

// 	var r0 *models.Issue
// 	var r1 error
// 	if rf, ok := ret.Get(0).(func(string) (*models.Issue, error)); ok {
// 		return rf(externalID)
// 	}
// 	if rf, ok := ret.Get(0).(func(string) *models.Issue); ok {
// 		r0 = rf(externalID)
// 	} else {
// 		if ret.Get(0) != nil {
// 			r0 = ret.Get(0).(*models.Issue)
// 		}
// 	}

// 	if rf, ok := ret.Get(1).(func(string) error); ok {
// 		r1 = rf(externalID)
// 	} else {
// 		r1 = ret.Error(1)
// 	}

// 	return r0, r1
// }

// GetIssueByKey provides a mock function with given fields: key
func (_m *IssueRepository) GetIssueByKey(key string) (*models.Issue, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetIssueByKey")
	}

	var r0 *models.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Issue, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Issue); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIssuesByProjectID provides a mock function with given fields: projectID, limit, offset
func (_m *IssueRepository) GetIssuesByProjectID(projectID int, limit int, offset int) ([]models.Issue, int, error) {
	ret := _m.Called(projectID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetIssuesByProjectID")
	}

	var r0 []models.Issue
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, int) ([]models.Issue, int, error)); ok {
		return rf(projectID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) []models.Issue); ok {
		r0 = rf(projectID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) int); ok {
		r1 = rf(projectID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int, int) error); ok {
		r2 = rf(projectID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateIssue provides a mock function with given fields: issue
// func (_m *IssueRepository) UpdateIssue(issue *models.Issue) error {
// 	ret := _m.Called(issue)

// 	if len(ret) == 0 {
// 		panic("no return value specified for UpdateIssue")
// 	}

// 	var r0 error
// 	if rf, ok := ret.Get(0).(func(*models.Issue) error); ok {
// 		r0 = rf(issue)
// 	} else {
// 		r0 = ret.Error(0)
// 	}

// 	return r0
// }

// UpdateIssueWithHistory provides a mock function with given fields: issue, fromStatus
func (_m *IssueRepository) UpdateIssueWithHistory(issue *models.Issue, fromStatus string) error {
	ret := _m.Called(issue, fromStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIssueWithHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Issue, string) error); ok {
		r0 = rf(issue, fromStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIssueRepository creates a new instance of IssueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssueRepository {
	mock := &IssueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
