run:
  timeout: 5m
  tests: false
  go: '1.24'

output:
  formats:
    - format: tab

linters:
  disable-all: true
  enable:
    - shadow
    - govet
    - revive
    - errcheck
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
    - misspell
    - whitespace

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true