version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dev_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Database/init_scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: dev_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    build: ./Kafka
    container_name: dev_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  backend:
    build: ./Backend
    container_name: dev_backend
    restart: unless-stopped
    environment:
      # - KAFKA_BROKERS=kafka:9092

      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started

  connector:
    build: ./Connector
    container_name: dev_connector
    restart: unless-stopped
    environment:
      # - KAFKA_BROKERS=kafka:9092

      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_started

  ui:
    build: ./UI
    container_name: dev_ui
    restart: unless-stopped
    ports:
      - "3000:80"

volumes:
  pgdata:
