version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - wsl_v5
    - errorlint
    - govet
    - errcheck
    - staticcheck
    - wrapcheck
    - ineffassign
    - unused
    - whitespace
    - misspell
    - contextcheck
    - nakedret

formatters:
  enable:
    - goimports
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0