version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8000:8000"
      - "2345:2345" # Порт для Delve
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
