ALTER TABLE projects RENAME COLUMN title TO name;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS url TEXT NOT NULL DEFAULT '';
ALTER TABLE issues RENAME COLUMN created_time TO created;
ALTER TABLE issues RENAME COLUMN updated_time TO updated;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS changelog JSONB;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT
);

ALTER TABLE issues ALTER COLUMN external_id DROP NOT NULL;