// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/microservices-development-hse/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// AnalyticsService is an autogenerated mock type for the AnalyticsService type
type AnalyticsService struct {
	mock.Mock
}

// GetLatestSnapshot provides a mock function with given fields: ctx, projectID, reportType
func (_m *AnalyticsService) GetLatestSnapshot(ctx context.Context, projectID int, reportType string) (*models.AnalyticsSnapshot, error) {
	ret := _m.Called(ctx, projectID, reportType)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSnapshot")
	}

	var r0 *models.AnalyticsSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*models.AnalyticsSnapshot, error)); ok {
		return rf(ctx, projectID, reportType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *models.AnalyticsSnapshot); ok {
		r0 = rf(ctx, projectID, reportType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AnalyticsSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, projectID, reportType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunFullAnalysis provides a mock function with given fields: projectID
func (_m *AnalyticsService) RunFullAnalysis(projectID int) {
	_m.Called(projectID)
}

// NewAnalyticsService creates a new instance of AnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsService {
	mock := &AnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
