// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/microservices-development-hse/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ConnectorService is an autogenerated mock type for the ConnectorService type
type ConnectorService struct {
	mock.Mock
}

// FetchRemoteProjects provides a mock function with no fields
func (_m *ConnectorService) FetchRemoteProjects() ([]models.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchRemoteProjects")
	}

	var r0 []models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TriggerProjectImport provides a mock function with given fields: projectKey
func (_m *ConnectorService) TriggerProjectImport(projectKey string) error {
	ret := _m.Called(projectKey)

	if len(ret) == 0 {
		panic("no return value specified for TriggerProjectImport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(projectKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConnectorService creates a new instance of ConnectorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectorService {
	mock := &ConnectorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
