// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/microservices-development-hse/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// IssueService is an autogenerated mock type for the IssueService type
type IssueService struct {
	mock.Mock
}

// GetIssueDetails provides a mock function with given fields: key
func (_m *IssueService) GetIssueDetails(key string) (*models.Issue, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetIssueDetails")
	}

	var r0 *models.Issue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Issue, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Issue); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIssuesByProject provides a mock function with given fields: projectID, limit, page
func (_m *IssueService) GetIssuesByProject(projectID int, limit int, page int) ([]models.Issue, int, error) {
	ret := _m.Called(projectID, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetIssuesByProject")
	}

	var r0 []models.Issue
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, int) ([]models.Issue, int, error)); ok {
		return rf(projectID, limit, page)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) []models.Issue); ok {
		r0 = rf(projectID, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) int); ok {
		r1 = rf(projectID, limit, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int, int) error); ok {
		r2 = rf(projectID, limit, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIssueService creates a new instance of IssueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssueService {
	mock := &IssueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
