// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/microservices-development-hse/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ProjectService is an autogenerated mock type for the ProjectService type
type ProjectService struct {
	mock.Mock
}

// CreateProject provides a mock function with given fields: key, title, url
func (_m *ProjectService) CreateProject(key string, title string, url string) (*models.Project, error) {
	ret := _m.Called(key, title, url)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*models.Project, error)); ok {
		return rf(key, title, url)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *models.Project); ok {
		r0 = rf(key, title, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(key, title, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProject provides a mock function with given fields: id
func (_m *ProjectService) DeleteProject(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: id
func (_m *ProjectService) Exists(id int) (bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectDetails provides a mock function with given fields: id
func (_m *ProjectService) GetProjectDetails(id int) (*models.Project, map[string]interface{}, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectDetails")
	}

	var r0 *models.Project
	var r1 map[string]interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (*models.Project, map[string]interface{}, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Project); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(int) map[string]interface{}); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetProjectsList provides a mock function with given fields: limit, page
func (_m *ProjectService) GetProjectsList(limit int, page int) ([]models.Project, int, error) {
	ret := _m.Called(limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectsList")
	}

	var r0 []models.Project
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]models.Project, int, error)); ok {
		return rf(limit, page)
	}
	if rf, ok := ret.Get(0).(func(int, int) []models.Project); ok {
		r0 = rf(limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = rf(limit, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(limit, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateProject provides a mock function with given fields: id, key, title
func (_m *ProjectService) UpdateProject(id int, key string, title string) (*models.Project, error) {
	ret := _m.Called(id, key, title)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string, string) (*models.Project, error)); ok {
		return rf(id, key, title)
	}
	if rf, ok := ret.Get(0).(func(int, string, string) *models.Project); ok {
		r0 = rf(id, key, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = rf(id, key, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProjectService creates a new instance of ProjectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectService {
	mock := &ProjectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
